### ISSUE TITLE
eRROR

### ISSUE THREAD

**Issue by Hamster-lord** [remance/Masendor#28] opened 2022-11-01 00:37 UTC
!! Traceback (most recent call last):
!!   File "/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.3.5 2/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.3.5 2/gamescript/game.py", line 218, in __init__
    os.makedirs("/profile")
!!   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
!! OSError: [Errno 30] Read-only file system: '/profile'

**Comment by remance** [comment] 2022-11-01 02:14
Seem like the issue is that the game folder (Masendor-0.6.3.5 2) is in read only, so the game cannot create folder inside it. Can you check if that is the case?

**Comment by remance** [comment] 2022-11-01 03:24
Or maybe you can try moving the game folder to another location that does not have permission locked.

**Comment by Hamster-lord** [comment] 2022-11-01 21:39
ok

**Comment by Hamster-lord** [comment] 2022-11-01 21:58
now this is happening
!! Traceback (most recent call last):
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/gamescript/game.py", line 640, in __init__
    self.genre_ui_dict = make_genre_specific_ui(self.main_dir, self.screen_scale, self.genre)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/gamescript/common/game/setup/make_genre_specific_ui.py", line 8, in make_genre_specific_ui
    genre_battle_ui_image = load_images(main_dir, screen_scale, [genre, "ui", "battle_ui"], load_order=False)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/gamescript/common/utility.py", line 63, in load_images
    load_order_file = [f for f in os.listdir(dir_path) if f.endswith("." + "png")]  # read all file
!! FileNotFoundError: [Errno 2] No such file or directory: '/users/emma/pycharmprojects/masendor 2.0/masendor-0.6.3.5/gamescript/common/ui/battle_ui'

**Comment by remance** [comment] 2022-11-02 04:16
This is very weird, this issue does not happen to me even if I download from the release. Would it be possible for you to add print(self.main_dir) to around line 160 of game.py file? Then it should be print out if this is the issue I am thinking of.

**Comment by remance** [comment] 2022-11-02 04:18
Or if you are using text editor with no line indication put that after 
    def __init__(self, main_dir, error_log):
        pygame.init()  # Initialize pygame
        pygame.mouse.set_visible(False)  # set mouse as not visible, use in-game mouse sprite
        self.main_dir = main_dir
        (Put print here)

**Comment by Hamster-lord** [comment] 2022-11-02 18:10
I got this: /Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5

**Comment by remance** [comment] 2022-11-03 02:49
Well this look to be correct. I have no idea why it put gamescript folder on your version. I will keep having a look to see if this happen in other computer as well. Just to make sure, this is the download from the last release version, correct?

**Comment by Hamster-lord** [comment] 2022-11-03 12:55
yes
It says 0.6.3.5

**Comment by Hamster-lord** [comment] 2022-11-03 16:07
In the main.py file it also says 
"/Users/Emma/PycharmProjects/Masendor 2.0/venv/bin/python" "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/main.py"
pygame 2.1.2 (SDL 2.0.18, Python 3.8.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5
Traceback (most recent call last):
  File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
  File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/gamescript/game.py", line 641, in __init__
    self.genre_ui_dict = make_genre_specific_ui(self.main_dir, self.screen_scale, self.genre)
  File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/gamescript/common/game/setup/make_genre_specific_ui.py", line 8, in make_genre_specific_ui
    genre_battle_ui_image = load_images(main_dir, screen_scale, [genre, "ui", "battle_ui"], load_order=False)
  File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5/gamescript/common/utility.py", line 63, in load_images
    load_order_file = [f for f in os.listdir(dir_path) if f.endswith("." + "png")]  # read all file
FileNotFoundError: [Errno 2] No such file or directory: '/users/emma/pycharmprojects/masendor 2.0/masendor-0.6.3.5/gamescript/common/ui/battle_ui'

**Comment by remance** [comment] 2022-11-03 16:37
Can't seem to replicate the issue even on other computer. Can you instead try print(main_dir) in make_genre_specific_ui.py? it should be in common/game/setup/.

**Comment by Hamster-lord** [comment] 2022-11-03 18:40
I got /Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.5

**Comment by Hamster-lord** [comment] 2022-11-03 19:01
Also there is no battle_ui in /users/emma/pycharmprojects/masendor 2.0/masendor-0.6.3.5/gamescript/common/ui/battle_ui

**Comment by remance** [comment] 2022-11-04 03:03
Yeah the issue is that it use gamescript folder path for no reason when no part of the code should make it do that. Even weirder that the prior loading works fine before this error occur.

**Comment by remance** [comment] 2022-11-04 05:40
I add a new release version. Not sure if this error will be fixed properly though.

**Comment by Hamster-lord** [comment] 2022-11-04 14:27
!! Traceback (most recent call last):
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16/gamescript/game.py", line 686, in __init__
    self.change_game_genre(self.genre)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16/gamescript/game.py", line 860, in change_game_genre
    genre_setting = importlib.import_module("gamescript" + new_genre + "genre_setting")
!!   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
!! ModuleNotFoundError: No module named 'gamescript/users/emma/pycharmprojects/masendor 2'

**Comment by remance** [comment] 2022-11-04 14:54
For reference, what OS are you using?

**Comment by remance** [comment] 2022-11-04 15:15
by the way did you edit some parts of the code? The error that say genre_setting = importlib.import_module("gamescript" + new_genre + "genre_setting") is genre_setting = importlib.import_module("gamescript." + new_genre + ".genre_setting"). It miss two dots in there for some reason. Maybe you can check if the dot still in the game.py file?

**Comment by Hamster-lord** [comment] 2022-11-04 18:32
Oh I did delete the two dots

**Comment by Hamster-lord** [comment] 2022-11-04 18:33
now this is happening

**Comment by Hamster-lord** [comment] 2022-11-04 18:33
!! Traceback (most recent call last):
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16/gamescript/game.py", line 686, in __init__
    self.change_game_genre(self.genre)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16/gamescript/game.py", line 860, in change_game_genre
    genre_setting = importlib.import_module("gamescript." + new_genre + ".genre_setting")
!!   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
!!   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
!!   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
!!   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
!!   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
!! ModuleNotFoundError: No module named 'gamescript./users/emma/pycharmprojects/masendor 2'

**Comment by Hamster-lord** [comment] 2022-11-04 18:34
macOS monterey version 12.1

**Comment by remance** [comment] 2022-11-05 02:43
ok if I have to guess the issue is that importlib.import_module work differently in macOS. So what I will try next is trying to test the game on both virtual macOS and Ubuntu. Even if I delete the dots the error is still different for yours (ModuleNotFoundError: No module named 'gamescriptarcadegenre_setting'). OR maybe I just have to compile the game in the appropriate OS to make it compatible.

**Comment by Hamster-lord** [comment] 2022-11-07 15:27
ok

**Comment by Hamster-lord** [comment] 2022-11-07 15:27
Please tell me when you are finished

**Comment by remance** [comment] 2022-11-07 16:32
Sure, so far I have finished with Linux testing and going to do macOS next.

**Comment by Hamster-lord** [comment] 2022-11-07 17:05
ok

**Comment by Hamster-lord** [comment] 2022-11-08 00:21
any luck>

**Comment by remance** [comment] 2022-11-08 08:16
Working on it. Having a bit of trouble installing some python module in macOS for some reason.

**Comment by remance** [comment] 2022-11-08 11:56
ok I manage to make it work. MacOS 12 version is in the release with the name Mac_Dream.Decision.0.6.3.16.zip. Let me know if it does not work on your system.

**Comment by Hamster-lord** [comment] 2022-11-08 20:16
how do you use the package

**Comment by Hamster-lord** [comment] 2022-11-08 20:19
also still no work

**Comment by Hamster-lord** [comment] 2022-11-08 20:19
!! Traceback (most recent call last):
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16m7/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16m7/gamescript/game.py", line 704, in __init__
    self.create_unit_slot(0, 0, range(0, 64), start_pos)  # make player custom unit slot
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16m7/gamescript/common/game/create_unit_slot.py", line 7, in create_unit_slot
    dummy_subunit = subunit.EditorSubunit(troop_id, game_id, self.unit_build_slot,
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-0.6.3.16m7/gamescript/subunit.py", line 702, in __init__
    self.image = self.block
!! AttributeError: 'EditorSubunit' object has no attribute 'block'

**Comment by remance** [comment] 2022-11-09 03:01
It is quite bizarre that you keep getting new error. I just use pyinstaller to compile the game on MacOS in virtual machine and test it in there. This error used to happen to me but I fixed it before, I will have a look.

**Comment by remance** [comment] 2022-11-09 06:01
As usual I can't seem to replicate this problem on my MacOS even with clean download from release. How did you run them game in your system, main.py on pycharm or main.exec directly?

**Comment by Hamster-lord** [comment] 2022-11-09 15:10
I ran main.py

**Comment by remance** [comment] 2022-11-09 16:05
If you download Mac_Dream.Decision.0.6.3.16.zip, then it is correct. Can you try run main.exec?

**Comment by remance** [comment] 2022-11-09 16:10
actually how come there is main.py in the release download? I don't think it is in there.

**Comment by remance** [comment] 2022-11-10 03:46
Ah I guess you didn't download the game from release but rather from the front page but still it is weird that it still give you error when it not on mine. What I refer to is from here: https://github.com/remance/Masendor/releases/tag/0.6.3.16m7

**Comment by remance** [comment] 2022-11-10 04:07
Oh I think there may be another possible cause for the error. It seem you are using python 3.8 to run the game. Can you try update it to 3.10 and install modules with the exact version as in requirements?

**Comment by Hamster-lord** [comment] 2022-11-19 02:46
ok

**Comment by Hamster-lord** [comment] 2022-11-19 02:56
still doesn't work

**Comment by Hamster-lord** [comment] 2022-11-19 14:38
also I'm getting this:
!! Traceback (most recent call last):
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-main/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-main/gamescript/game.py", line 702, in __init__
    self.create_unit_slot(0, 0, range(0, 64), start_pos)  # make player custom unit slot
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-main/gamescript/common/game/create_unit_slot.py", line 7, in create_unit_slot
    dummy_subunit = subunit.EditorSubunit(troop_id, game_id, self.unit_build_slot,
!!   File "/Users/Emma/PycharmProjects/Masendor 2.0/Masendor-main/gamescript/subunit.py", line 698, in __init__
    self.image = self.block
!! AttributeError: 'EditorSubunit' object has no attribute 'block'

**Comment by remance** [comment] 2022-11-19 22:06
Look like the same as previous error to me. To install requirement use command “pip install -r requirements.txt” either in pycharm terminal or mac terminal depend ming on how you run the game. You may also need to setup configuration in pycharm to use python 3.10 instead of 3.8 too if you did not do that yet.

**Comment by remance** [comment] 2022-11-19 22:11
The terminal for requirements installation need to be in the game directory too by the way.

**Comment by Hamster-lord** [comment] 2022-11-20 21:57
I already got the all the requirements

**Comment by Hamster-lord** [comment] 2022-11-21 00:03
but it still no work

**Comment by remance** [comment] 2022-11-21 08:03
Can you check if your pycharm project still use python 3.8 to run the game or not? If nothing really work, can you try launch the game from main.exec in mac release instead? It would help me know if the problem come from module issue or os related.

**Comment by Hamster-lord** [comment] 2022-11-22 00:46
Also when you go to Customize does the thing below keymap say mac OS?

**Comment by remance** [comment] 2022-11-22 07:43
Unfortunately I can't check my macOS until next month. By configuration do you mean in pycharm project configuartion? Here is mine in windows (if it helpful).

![image](https://user-images.githubusercontent.com/25480944/203254573-37afb498-2b98-46fc-ab96-ac91185ff77e.png)

**Comment by Hamster-lord** [comment] 2022-11-22 15:55
no

**Comment by Hamster-lord** [comment] 2022-11-22 15:55
in the main menu

**Comment by remance** [comment] 2022-11-22 16:10
No idea what you mean by main menu. Can you post screenshot?

**Comment by Hamster-lord** [comment] 2022-11-22 22:39
<img width="912" alt="Screen Shot 2022-11-22 at 4 39 18 PM" src="https://user-images.githubusercontent.com/114705212/203435759-46e1d1df-8382-4ed2-afaf-d4e0d2c1abed.png">

**Comment by remance** [comment] 2022-11-23 07:46
That setting affect only the keyboard key mapping I think. So that is probably correct setting.

**Comment by remance** [comment] 2022-11-23 08:06
Not quite sure if it different from mac pycharm or not but the configuration I meant is the one where you run the project. 

![image](https://user-images.githubusercontent.com/25480944/203497413-e0e2cf9f-fb6a-4ccc-b349-51e7ddbc239c.png)

**Comment by Hamster-lord** [comment] 2022-11-25 20:22
oh wait did you open it on github

**Comment by remance** [comment] 2022-11-25 20:40
No, I have the project in my local folder.

**Comment by Hamster-lord** [comment] 2022-11-26 23:55
ok

**Comment by Hamster-lord** [comment] 2022-11-27 00:27
It works now, but it's very slow and most of the maps don't work

**Comment by Hamster-lord** [comment] 2022-11-27 00:28
and a lot of errors

**Comment by Hamster-lord** [comment] 2022-11-27 00:29
!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/Masendor/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 718, in __init__
    self.run()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 1110, in run
    self.menu_map_select(mouse_left_up, mouse_left_down, mouse_scroll_up, mouse_scroll_down, esc_press)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/menu_map_select.py", line 62, in menu_map_select
    self.change_to_source_selection_menu()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/change_to_source_selection_menu.py", line 44, in change_to_source_selection_menu
    team_army, team_leader = self.read_battle_source(
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/read_battle_source.py", line 12, in read_battle_source
    self.team_pos[row["Team"]].append([int(item) for item in row["POS"].split(",")])
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/read_battle_source.py", line 12, in <listcomp>
    self.team_pos[row["Team"]].append([int(item) for item in row["POS"].split(",")])
!! ValueError: invalid literal for int() with base 10: ''

**Comment by remance** [comment] 2022-11-27 06:38
How did you fix it? And yeah most of maps not working right now after I start implementing arcade mode. Only try testmap for now. 

By the way did you try disable animation in the option menu yet? Hopefully it should help make the game faster a bit.

**Comment by Hamster-lord** [comment] 2022-11-27 14:49
I got this while trying to use testmap in tactical:
2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 08:47 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/Masendor/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 718, in __init__
    self.run()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 1113, in run
    self.menu_team_select(mouse_left_up, mouse_left_down, mouse_scroll_up, mouse_scroll_down, esc_press)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/menu_team_select.py", line 78, in menu_team_select
    self.start_battle()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/start_battle.py", line 11, in start_battle
    self.battle_game.run_game()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/battle.py", line 587, in run_game
    self.change_battle_state()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/tactical/battle/change_battle_state.py", line 46, in change_battle_state
    this_subunit.start_set(self.camera_zoom, self.subunit_animation_pool)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/subunit/start_set.py", line 8, in start_set
    self.swap_weapon()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/subunit/swap_weapon.py", line 43, in swap_weapon
    self.process_trait_skill()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/subunit/process_trait_skill.py", line 11, in process_trait_skill
    self.skill = skill_convert(self, self.skill, add_charge_skill=True)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/subunit/process_trait_skill.py", line 34, in skill_convert
    skill_dict = skill_dict | leader_skill_dict
!! TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by remance** [comment] 2022-11-27 16:19
The operand type(s) for |: 'dict' and 'dict' error should not happen unless you use python older than version 3.9. Did you still use python 3.8?

**Comment by Hamster-lord** [comment] 2022-11-27 22:06
yes

**Comment by Hamster-lord** [comment] 2022-11-27 22:11
it works now

**Comment by Hamster-lord** [comment] 2022-11-27 22:11
but how to control your characters

**Comment by Hamster-lord** [comment] 2022-11-28 00:51
2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-11-27 18:49 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/Masendor/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 718, in __init__
    self.run()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 1113, in run
    self.menu_team_select(mouse_left_up, mouse_left_down, mouse_scroll_up, mouse_scroll_down, esc_press)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/menu_team_select.py", line 78, in menu_team_select
    self.start_battle()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/start_battle.py", line 11, in start_battle
    self.battle_game.run_game()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/battle.py", line 942, in run_game
    self.subunit_updater.update(self.current_weather, self.dt, self.camera_zoom,
!!   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pygame/sprite.py", line 539, in update
    sprite.update(*args, **kwargs)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/subunit.py", line 588, in update
    self.status_update(weather=weather)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/subunit/status_update.py", line 207, in status_update
    self.special_effect[effect][0][1] = True
!! KeyError: 2

**Comment by remance** [comment] 2022-11-28 07:38
Depend which mode you play. If tactical you can move them similar to other rts. If arcade mode move them via wasd and mouse click for attack. Which map the last error occur?

**Comment by Hamster-lord** [comment] 2022-11-28 14:51
I think it was tactical

**Comment by remance** [comment] 2022-11-28 21:34
Ok this error should be fixed in the new update. Thanks for the report.

**Comment by Hamster-lord** [comment] 2022-11-29 18:45
ok

**Closed** 2022-12-11 15:23 UTC
