### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hamster-lord** [remance/Masendor#32] opened 2023-01-30 01:09 UTC
Ruleset: Historical, Mode: arcade
 Map: Testmap, Source: Modern Historians, Character: 1
!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/main.py", line 12, in <module>
    game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/game.py", line 739, in __init__
    self.run()
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/game.py", line 1150, in run
    self.menu_char_select(mouse_left_up, mouse_left_down, mouse_scroll_up,
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/common/game/menu_char_select.py", line 26, in menu_char_select
    self.start_battle(self.char_selected)
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/common/game/start_battle.py", line 9, in start_battle
    self.battle_game.prepare_new_game(self.ruleset, self.ruleset_folder, self.team_selected,
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/battle.py", line 534, in prepare_new_game
    self.subunit_animation_pool = self.main.create_sprite_pool(direction_list, self.main.troop_sprite_size,
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/common/game/create_sprite_pool.py", line 13, in create_sprite_pool
    weapon_common_type_list = tuple(set(["_" + value["Common"] + "_" for key, value in weapon_list.items() if
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/common/game/create_sprite_pool.py", line 13, in <listcomp>
    weapon_common_type_list = tuple(set(["_" + value["Common"] + "_" for key, value in weapon_list.items() if
!! TypeError: can only concatenate str (not "int") to str

**Comment by remance** [comment] 2023-01-30 12:32
Thanks for the report, This error should be fixed with the newest update. Made a mistake not checking for the error before commit :P

**Comment by Hamster-lord** [comment] 2023-02-06 01:05
I got this:
Ruleset: Historical, Mode: arcade
 Map: Testmap, Source: Modern Historians, Character: 1
!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/main.py", line 12, in <module>
    game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/game.py", line 744, in __init__
    self.run()
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/game.py", line 1150, in run
    self.menu_char_select(mouse_left_up, mouse_left_down, mouse_scroll_up,
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/common/game/menu_char_select.py", line 26, in menu_char_select
    self.start_battle(self.char_selected)
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/common/game/start_battle.py", line 13, in start_battle
    self.battle_game.run_game()
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/battle.py", line 892, in run_game
    pygame.mixer.music.load(self.musiclist[self.music_current[self.picked_music]])
!! IndexError: list index out of range

**Comment by remance** [comment] 2023-02-08 16:12
yeah I notice this error. Although I can't commit the update I am working yet. Will let you know when it done.

**Comment by Hamster-lord** [comment] 2023-02-09 03:25
ok thx

**Comment by remance** [comment] 2023-02-09 13:27
The new update should fix this issue now.

**Comment by Hamster-lord** [comment] 2023-02-09 20:07
why is there a black box around the caracthers?

**Comment by Hamster-lord** [comment] 2023-02-09 20:07
or soldiers

**Comment by remance** [comment] 2023-02-10 19:15
Is it still there? I don't see any.

**Comment by Hamster-lord** [comment] 2023-02-11 14:26
<img width="1280" alt="Screen Shot 2023-02-11 at 8 25 15 AM" src="https://user-images.githubusercontent.com/114705212/218263220-740c829a-31b8-42bf-b44b-45abc75ba1fe.png">

**Comment by Hamster-lord** [comment] 2023-02-11 14:27
also how to change weapons?

**Comment by remance** [comment] 2023-02-11 15:40
Well that is very weird. Wonder if it related to pygame version or macOS. This never happen in the previous version before rework update right?

To change your character weapon, just press 1 or 2 (the one not on numpad).

**Comment by Hamster-lord** [comment] 2023-02-13 01:47
yes

**Comment by remance** [comment] 2023-02-14 13:38
For the weird black box, can you try run this code below?

class HeroUI(pygame.sprite.Sprite):
    weapon_sprite_pool = None

    def __init__(self, screen_scale, ):
        self._layer = 10
        pygame.sprite.Sprite.__init__(self)
        self.screen_scale = screen_scale

        self.image = pygame.Surface((200 * self.screen_scale[0], 200 * self.screen_scale[1]), pygame.SRCALPHA)

        self.health_bar_size = (10 * self.screen_scale[0], self.image.get_height())
        self.health_bar = pygame.Surface(self.health_bar_size, pygame.SRCALPHA)
        self.health_bar.fill((0, 0, 0))
        self.health_bar_original = self.health_bar.copy()
        self.health_bar_rect = self.health_bar.get_rect(topright=(self.image.get_width() - self.health_bar_size[0], 0))
        self.health_bar.fill((200, 0, 0))

        self.health_bar_height = self.health_bar.get_height()

        self.stamina_bar = pygame.Surface(self.health_bar_size, pygame.SRCALPHA)
        self.stamina_bar.fill((0, 0, 0))
        self.stamina_bar_original = self.stamina_bar.copy()
        self.stamina_bar_rect = self.stamina_bar.get_rect(topright=(self.image.get_width(), 0))
        self.stamina_bar.fill((0, 200, 0))

        self.image.blit(self.health_bar, self.health_bar_rect)
        self.image.blit(self.stamina_bar, self.stamina_bar_rect)

        self.rect = self.image.get_rect(topleft=(0, 0))

import pygame

pygame.init()
wndsize = (400, 400)
window = pygame.display.set_mode(wndsize)
clock = pygame.time.Clock()

test = HeroUI((1, 1))
run = True
while run:
    clock.tick(60)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            run = False
    window.fill((255, 255, 255))

    window.blit(test.image, test.rect)

    pygame.display.update()

**Comment by Hamster-lord** [comment] 2023-02-17 03:20
where?

**Comment by Hamster-lord** [comment] 2023-02-17 13:58
<img width="512" alt="Screen Shot 2023-02-17 at 7 57 49 AM" src="https://user-images.githubusercontent.com/114705212/219675327-94c9b38b-5642-47de-9534-33a4563c72ea.png">

**Comment by remance** [comment] 2023-02-17 15:50
seem to work fine on that end then. well this is quite weird since it use the same setup. Can you check in game again with the newest update to see if it still has the same bug?

**Comment by Hamster-lord** [comment] 2023-02-17 20:29
there are still black boxes

**Comment by remance** [comment] 2023-02-19 10:49
Tested the game on another pc and no black box issue. Guess it is likely related to macOS. Will have a test on that later.

**Comment by Hamster-lord** [comment] 2023-02-19 20:42
maybe

**Comment by Hamster-lord** [comment] 2023-03-05 01:27
Have you figured out why black boxes are appearing on my screen?

**Comment by Hamster-lord** [comment] 2023-03-05 02:14
I got !! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/main.py", line 15, in <module>
    game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/game.py", line 559, in __init__
    self.change_ruleset()
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/game.py", line 587, in change_ruleset
    self.troop_data, self.leader_data, self.faction_data = make_faction_troop_leader_data(self.main_dir,
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/common/game/setup/make_faction_troop_leader_data.py", line 12, in make_faction_troop_leader_data
    troop_data = datastat.TroopData(main_dir, weapon_images, ruleset_folder, language)
!!   File "/Users/Emma/Documents/GitHub/AnchientBattleSimulator/gamescript/datastat.py", line 252, in __init__
    self.weapon_lore |= {key: value for key, value in weapon_lore_list.items() if key
!! TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

**Comment by remance** [comment] 2023-03-05 04:36
Unfortunately not, I have no access to macOS to test it yet. The last error is because you need python 3.10 to run the game.

**Comment by Hamster-lord** [comment] 2023-03-06 14:44
oh ok

**Comment by Hamster-lord** [comment] 2023-03-13 18:58
did you get a macOS yet to test the error?

**Comment by remance** [comment] 2023-03-14 04:28
Probably will be a little while longer, I don't have access to my pc yet and my laptop is not good enough for virtual machine. Will let you know when I manage to do it. For now, can you try update the game and all python library to see if it work now?

**Comment by Hamster-lord** [comment] 2023-03-18 01:22
ok

**Comment by Hamster-lord** [comment] 2023-03-25 12:46
The black boxes might actually be hit boxes.

**Comment by Hamster-lord** [comment] 2023-03-25 12:46
I also found out the boxes size depends on the units size.

**Comment by remance** [comment] 2023-03-25 12:59
I see thanks for checking, well I should be able to test the game on macOS soon. Will let you know when I mange to get to it.

**Comment by remance** [comment] 2023-03-27 13:47
so I managed to run the game on macOS 12 in my virtual machine and could not manage to replicate the black box issue. So I think the issue may be from outdated requirement on your pycharm. Can you post a screenshot of your package list?

Here is what mine look like: For some reason pygame 2.3 can not be run on my macOS so I had to revert to 2.1 version.
![image](https://user-images.githubusercontent.com/25480944/227957403-fc641347-4ad9-453e-aa8a-484e7d2e6a43.png)

**Comment by remance** [comment] 2023-03-27 13:48
Well you should also try run pip install -r requirements.txt too to check if it really is the issue with library.

**Comment by remance** [comment] 2023-03-27 14:00
If that still not work, I will make a new release for macOS for you to test with the release version.

**Comment by Hamster-lord** [comment] 2023-03-30 13:43
it doesn't work

**Comment by remance** [comment] 2023-03-31 13:25
Just release mac version in the newest update. Can you try it from here? 

https://github.com/remance/Masendor/releases/tag/0.6.8.4

**Comment by Hamster-lord** [comment] 2023-04-02 15:04
it still doesn't work

**Comment by Hamster-lord** [comment] 2023-04-02 15:08
the background is has no green. it's just grey with curved lines everywhere.

**Comment by Hamster-lord** [comment] 2023-04-02 15:08
I can't even see the bases

**Comment by remance** [comment] 2023-04-02 15:15
Also can you post screenshot for the animation maker too?

**Comment by remance** [comment] 2023-04-03 02:50
So if this blackbox only appear in the newer version, I think this may solve the issue.

Can you try downgrade Pillow library from 9.4.0 to 9.3.0. And maybe all of the following libraries below to these specific version? Maybe the newer one are incompatible with your system.

iniconfig==1.1.1
numpy~=1.22.2
pandas~=1.4.1
Pillow~=9.3.0
pygame~=2.1.2
pyperclip==1.8.2
pywin32-ctypes==0.2.0
screeninfo~=0.8.1
pathfinding~=1.0.1
scipy~=1.8.0

**Comment by Hamster-lord** [comment] 2023-04-04 01:58
<img width="678" alt="Screen Shot 2023-04-03 at 8 58 04 PM" src="https://user-images.githubusercontent.com/114705212/229666769-2f2e6562-2fab-48c9-a93e-c70c8994b431.png">

**Comment by remance** [comment] 2023-04-04 03:16
Thank you for the screenshot, the black box around mouse icon make it more obvious now that there is some issue with transparency. Likely with pygame and your system for some reason. I will have a try to make a quick test for this.

**Comment by remance** [comment] 2023-04-04 03:25
What happen when you run Aliens.py game? You can find it in python folder (not sure where it is in your macOS system). Here is an example of where mine is : C:\Program Files (x86)\Python\Lib\site-packages\pygame\examples

**Comment by remance** [comment] 2023-04-04 03:27
In any case, can you post your system spec, the pygame version you are running on? If nothing is working, I think I will have to go ask in a forum or pygame issue.

**Comment by remance** [comment] 2023-04-04 04:40
So I receive a suggestion to replace pygame with pygame-ce. So can you try update the game, and uninstall pygame from your pycharm and then install pygame-ce instead?

**Comment by Hamster-lord** [comment] 2023-04-06 01:03
aliens.py does not have any black boxes

**Comment by remance** [comment] 2023-04-06 02:52
Did you try uninstall pygame and install "pygame-ce" instead yet?

**Comment by Hamster-lord** [comment] 2023-04-13 01:57
where is the folder that contains the soldiers

**Comment by remance** [comment] 2023-04-13 06:43
Well that is bad to hear :( Can you post screenshot of animation maker?

Do you mean the troop sprite or data (like attack stat and stuff)?

For sprite it is here: data\sprite\subunit

For data it is here: data\ruleset\historical\troop\preset

**Comment by remance** [comment] 2023-04-13 07:10
The issue is not related to troop itself though since even the mouse surface also not working.

**Comment by remance** [comment] 2023-04-13 07:30
Also I am going to submit this issue on pygame-ce github. Can you list the following info below?

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):
- **Python version** (e.g. 3.7.9, 3.8.5) : (Shown when run game)
- **SDL version** (e.g. SDL 2.0.12):  (Shown when run game)
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):  (Shown when run game)
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Comment by Hamster-lord** [comment] 2023-04-13 21:41
what do you meen?

**Comment by remance** [comment] 2023-04-14 03:50
> what do you meen?

To which comment are you asking this?

If you mean this one:

> Also I am going to submit this issue on pygame-ce github. Can you list the following info below?
> 
> * **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):
> * **Python version** (e.g. 3.7.9, 3.8.5) : (Shown when run game)
> * **SDL version** (e.g. SDL 2.0.12):  (Shown when run game)
> * **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):  (Shown when run game)
> * **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

Then I need your system information so I can ask the pygame developer to check with this issue we are having.

**Comment by Hamster-lord** [comment] 2023-04-18 21:59
my mouse and the game mouse does not align and I don't know how to do what you are asking me

**Comment by remance** [comment] 2023-04-19 09:18
You can get your computer system specification by following the step in this link: https://kb.wisc.edu/helpdesk/page.php?id=8208

![image](https://user-images.githubusercontent.com/25480944/233028986-aacffcab-057f-45fb-9074-c9b20fb52f32.png)

I need to know the information in graphic/display and the one shown in the image above.

Then I need to know your python version and all library version like the one in image below.

![image](https://user-images.githubusercontent.com/25480944/233029171-52e3e21c-cda3-4ac4-95da-7efe9a206a6e.png)

**Comment by Hamster-lord** [comment] 2023-04-20 22:26
There is no more info on my mac

**Comment by remance** [comment] 2023-04-21 05:47
That is weird. Do you have other computer to test the game?

**Comment by remance** [comment] 2023-04-21 18:15
Now that I think about it, have you try testing other games made in pygame so far?

**Comment by remance** [comment] 2023-04-21 18:22
Maybe try this one: https://ghastly.itch.io/meltdown or https://github.com/Gooodgis/dont-touch-my-presents or https://internal.markop1.cz/chess/

**Comment by Hamster-lord** [comment] 2023-04-22 16:07
I tried dont touch my presents before. It works like a charm!

**Comment by remance** [comment] 2023-04-22 17:47
Well this is even weirder. Although the game use older version of pygame. I wonder why this game does not work when both use pygame.

**Comment by Hamster-lord** [comment] 2023-04-23 02:21
yeah

**Comment by Hamster-lord** [comment] 2023-04-24 01:24
tHE BLACK BOXES ARE REMOVED I THINK, BUT THE BACKGROUND ISN'T LOADING PROPERLY. The background loads properly when you just start the battle, but after about 1 second, the background changes into a more lazy version of the background.

**Comment by remance** [comment] 2023-04-24 02:58
Well somehow that one things fixed itself. Can you post 2 screenshots of before and after the background change?

**Comment by Hamster-lord** [comment] 2023-04-24 14:06
ok

**Comment by Hamster-lord** [comment] 2023-04-25 00:00
You should add romans and make the game kind of similar to shield wall on steam: https://store.steampowered.com/app/1216320/Shieldwall/ , because romans were very cool and popular and you should know that romans were pretty famous for their shield wall.

**Comment by remance** [comment] 2023-04-25 02:58
Hmm yes roman battle would be a great addition. What do you think is more interesting, Romans vs barbarian (german or celt), vs carthage, parthia, egypt, greek, or maybe against roman themselves (civil war)?

**Comment by RybenHill** [comment] 2023-04-25 10:18
> Hmm yes roman battle would be a great addition. What do you think is more interesting, Romans vs barbarian (german or celt), vs carthage, parthia, egypt, greek, or maybe against roman themselves (civil war)?

A whole campaign against them all ;)

**Comment by Hamster-lord** [comment] 2023-04-25 14:43
yes

**Comment by remance** [comment] 2023-04-26 02:54
Well if have enough time, sure. At least it is possible to reuse roman troops in all those battle. :)

**Comment by Hamster-lord** [comment] 2023-04-26 16:26
> before <img alt="Screen Shot 2023-04-24 at 9 08 42 AM" width="678" src="https://user-images.githubusercontent.com/114705212/234021832-726ee05d-de83-4b78-aeec-220c4b6a97ce.png"> after <img alt="Screen Shot 2023-04-24 at 9 08 25 AM" width="678" src="https://user-images.githubusercontent.com/114705212/234022011-a8810bbb-272e-4da6-b50d-4bfeb3657cd9.png">

Can you solve this?

**Comment by Hamster-lord** [comment] 2023-04-26 16:27
Also. I can't use the map editor.

**Comment by RybenHill** [comment] 2023-04-26 17:31
Hello @Hamster-lord 

Is the original Issue with the black boxes solved?

Can we consider that bug fixed, so we can close this issue ticket?
Would it be possible that you report every bug in a different issue ticket? 
Like, what do you do to trigger the bug, does it happen 100% of the times with those stepes?
I think it's going to be easier to track and fix them that way.

Thanks!

**Comment by remance** [comment] 2023-04-26 18:48
> > before <img alt="Screen Shot 2023-04-24 at 9 08 42 AM" width="678" src="https://user-images.githubusercontent.com/114705212/234021832-726ee05d-de83-4b78-aeec-220c4b6a97ce.png"> after <img alt="Screen Shot 2023-04-24 at 9 08 25 AM" width="678" src="https://user-images.githubusercontent.com/114705212/234022011-a8810bbb-272e-4da6-b50d-4bfeb3657cd9.png">
> 
> Can you solve this?

Even the before image already doesn't look right. So I think something is wrong with map effect instead now. I will have a try to fix it.

**Comment by RybenHill** [comment] 2023-04-26 20:46
@remance can you show a screenshot of how it should look like? (ie., how it looks on your local computer)

What's the macOS version you are uding @Hamster-lord ?
What about the python interpreter version and the rest of the python libraries?

I can try myself to trigger the bug in a VM with the problem environment, but first I need to know the details to reproduce it in the same circumstances.
Any information will be of help.

**Comment by Hamster-lord** [comment] 2023-04-27 01:31
12.6.3

**Comment by remance** [comment] 2023-04-27 03:57
@RybenHill 

Here is what mine look like before and after the snow weather effect got added. Actually my previous was misinformed before. The before image seem to be what the game look like few second before the weather effect kick in. And I can see that the blackbox issue is not really fully solved yet. I can still see blackbox around the snow sprite on Hamster-lord screenshot. So there is something between different between the way image is loaded for troops and other sprites that fix the black box issue.

![image](https://user-images.githubusercontent.com/25480944/234755416-134df114-5e44-43df-b358-4f2921f7d882.png)

**Comment by remance** [comment] 2023-04-27 04:07
@Hamster-lord ok I just tried something. Can you update the game and have a test again? I think it should (hopefully) fix your issue.

**Comment by remance** [comment] 2023-04-27 04:15
If the new update still does not work. Can you screen shot what this part look like on your system?

![image](https://user-images.githubusercontent.com/25480944/234757967-0f56783f-5db8-4f54-88b1-65222dd5ca53.png)

**Comment by Hamster-lord** [comment] 2023-04-28 00:51
<img width="1280" alt="Screen Shot 2023-04-27 at 7 51 06 PM" src="https://user-images.githubusercontent.com/114705212/235028763-ee6803cf-0714-4842-8629-49c036587c4b.png">
not working

**Comment by Hamster-lord** [comment] 2023-04-28 00:52
this is for huge battle

**Comment by remance** [comment] 2023-04-28 04:23
So two things I manage to derive from the last screenshot. The sprite transparency work fine **IF** they are blitted on to another surface first (for example weapon icon on top left UI). The transparency issue seem to occur mostly for sprite that are blit on UI interface mostly. But I am not sure why map weather effect transparency also does not work. At least this narrow down what to look for.

**Comment by remance** [comment] 2023-04-28 04:28
OK for the next step, Can you post what this screen look like on your system?

![image](https://user-images.githubusercontent.com/25480944/235054235-c3dd49f4-48cd-4845-8156-ab45fdda847c.png)

**Comment by Hamster-lord** [comment] 2023-04-29 15:13
for some reason, there is no settings under rename project

**Comment by Hamster-lord** [comment] 2023-04-29 15:14
never mind I found it

**Comment by Hamster-lord** [comment] 2023-04-29 15:14
<img width="997" alt="Screen Shot 2023-04-29 at 10 13 49 AM" src="https://user-images.githubusercontent.com/114705212/235310039-24d0762d-bcfc-44b1-aaee-760a2d15bc66.png">

**Comment by Hamster-lord** [comment] 2023-04-29 15:21
also, the new updates caused the black boxes to come back to the soldiers.

**Comment by remance** [comment] 2023-04-29 15:26
So first thing first, you need to uninstall pygame 2.3.0. Try run the game after that and see how it go.

**Comment by Hamster-lord** [comment] 2023-04-29 18:18
now it says No module named 'pygame.freetype'

**Comment by remance** [comment] 2023-04-30 04:17
did you delete pygame-ce as well? If so try reinstall only pygame-ce and try again.

**Comment by Hamster-lord** [comment] 2023-04-30 13:54
I still have pygame-ce installed

**Comment by remance** [comment] 2023-05-02 10:55
Ok, will try to do a bit more test. Will let you know when the next update is.

**Comment by remance** [comment] 2023-05-06 07:50
So here is what I found. You need to uninstall pygame-ce and reinstall it again to make the pygame import work properly.

**Comment by Hamster-lord** [comment] 2023-05-07 23:22
the black boxes are still there :(

**Comment by remance** [comment] 2023-05-08 08:03
Well that suck :l I wonder what fix the black box issue before. But it is not related to pygame-ce version for sure. Wonder if they actually manage to fix it on normal pygame. Maybe can you try remove pygame-ce and reinstall pygame only again?

**Comment by remance** [comment] 2023-05-11 03:23
> <img alt="Screen Shot 2023-04-27 at 7 51 06 PM" width="1280" src="https://user-images.githubusercontent.com/114705212/235028763-ee6803cf-0714-4842-8629-49c036587c4b.png">
> 
> not working

So it become similar to this image before, yes?

**Comment by Hamster-lord** [comment] 2023-05-13 00:34
correct!

**Closed** 2023-08-15 00:11 UTC
